// Isolated browser simulation: controls input and chooses only offered cards.
window.simulateBalance=async function(config){
 let rngState=config.seed>>>0;Math.random=()=>{rngState=(Math.imul(rngState,1664525)+1013904223)>>>0;return rngState/4294967296;};
 const ledger={dealt:0,taken:0,hits:0,revives:0,byWeapon:{},byEnemy:{},choices:[],snapshots:[],xpAwarded:0,healedByDamage:0,lowHPSeconds:0,stuckSeconds:0,guardianSpawns:[],guardianKills:[],killsByKind:{}};
 let currentSource=null;
 window.runLog={setSource(id){currentSource=id;},get currentSrc(){return currentSource;},begin(){},finish(){},tick(){},addSpawnType(){},onSpawn(){},onShieldBlock(){},onDamageDealt(amount,source){const key=source||currentSource||'unknown';ledger.dealt+=amount;ledger.byWeapon[key]=(ledger.byWeapon[key]||0)+amount;},onKill(kind){ledger.killsByKind[kind]=(ledger.killsByKind[kind]||0)+1;},onDamageTaken(amount,source,kind){ledger.taken+=amount;ledger.hits++;const key=kind||source||'unknown';ledger.byEnemy[key]=(ledger.byEnemy[key]||0)+amount;},onRevive(){ledger.revives++;}};
 meta.upgrades={};meta.difficulty=config.difficulty||'normal';meta.selectedChar=config.character||'aeloria';meta.characters=[meta.selectedChar];meta.hearts=[];meta.bannedWeapons=[];meta.bannedPassives=[];meta.weapons=[META_CHARS.find(c=>c.id===meta.selectedChar).startWeapon];meta.charStarts={[meta.selectedChar]:meta.weapons[0]};
 rerollWorldSeed();WORLD_SEED=config.seed;startGame();Sound.stopMusic();Sound.play=()=>{};game.running=false;setAutoLevelUp(true);
 if(config.preset==='midgame'){const p=game.player;game.time=300000;p.level=20;p.xp=0;p.xpToLevel=310;p.maxHp=p.hp=280;p.vamp=.3;p.regen=1;p.armor=5;p.dmgMult=1.5;p.cdMult=.75;p.weapons=['magicBolt','holyShield','fireBlast','lightning'].map(id=>({id,level:6,lastFired:0}));p.passives=[];}
 const originalPick=autoPick,originalGain=gainXp,originalDamage=damageEnemy,originalGuardian=spawnGuardian,originalKill=killEnemy;
 const rank={common:1,rare:1.35,epic:1.75,legendary:2.25};
 autoPick=function(choices){let pick;if(config.build==='auto')pick=originalPick(choices);else{const p=game.player;const score=c=>{let base=c.passive?({damage:38,cooldown:38,armor:42,regen:p.regen<.8?65:35,vampirism:p.vamp<.10?80:45,speed:p.speed<205?46:25,magnet:p.pickupRange<150?42:22,revive:p.revives===0?72:35,health:36,luck:24,growth:25,duplicator:40,glassCannon:8}[c.key]||22):(c.autoRank===0?47:p.weapons.length<3?64:28);if(c.passive&&RECIPES.some(r=>r.passive===c.key&&p.weapons.some(w=>w.id===r.weapon)&&!game.recipesTriggered[r.id]))base+=18;return base*(.75+.25*(rank[c.rarity]||1));};pick=choices.slice().sort((a,b)=>score(b)-score(a))[0];}if(pick)ledger.choices.push({seconds:+(game.time/1000).toFixed(1),level:game.player.level,key:pick.key,passive:!!pick.passive,rarity:pick.rarity});return pick;};
 gainXp=function(amount){ledger.xpAwarded+=amount;return originalGain(amount);};
 damageEnemy=function(...args){const before=game.player.hp;const value=originalDamage(...args);ledger.healedByDamage+=Math.max(0,game.player.hp-before);return value;};
 spawnGuardian=function(id){ledger.guardianSpawns.push({id,seconds:game.time/1000});return originalGuardian(id);};
 killEnemy=function(e){if(e.isGuardian)ledger.guardianKills.push({id:e.biomeId,seconds:game.time/1000});return originalKill(e);};
 const anchor={x:game.player.x,y:game.player.y};let path=[],pathTime=-Infinity,pathGoal=null,chosenGoal=null,nextSnapshot=30000,decision=0,previousPosition={...anchor};
 const passable=(x,y)=>!circleBlocked(x,y,game.player.radius);
 function navigate(goal){const p=game.player;if(game.time-pathTime>700||!pathGoal||Math.hypot(pathGoal.x-goal.x,pathGoal.y-goal.y)>100){pathTime=game.time;pathGoal={...goal};const startX=Math.floor(p.x/TILE),startY=Math.floor(p.y/TILE),gx=Math.round(clamp((goal.x-p.x)/TILE,-18,18)),gy=Math.round(clamp((goal.y-p.y)/TILE,-18,18));let end={x:gx,y:gy};const free=(x,y)=>passable((startX+x)*TILE+TILE/2,(startY+y)*TILE+TILE/2);if(!free(end.x,end.y)){let found=false;for(let r=1;r<=4&&!found;r++)for(let dx=-r;dx<=r&&!found;dx++)for(let dy=-r;dy<=r;dy++)if(free(gx+dx,gy+dy)){end={x:gx+dx,y:gy+dy};found=true;break;}}const key=(x,y)=>x+','+y,nodes=new Map(),open=[{x:0,y:0,g:0,f:Math.abs(end.x)+Math.abs(end.y),parent:null}];nodes.set('0,0',open[0]);let last=null;for(let work=0;open.length&&work<1500;work++){let best=0;for(let i=1;i<open.length;i++)if(open[i].f<open[best].f)best=i;const node=open.splice(best,1)[0];if(node.closed)continue;node.closed=true;if(node.x===end.x&&node.y===end.y){last=node;break;}for(const [dx,dy] of [[1,0],[-1,0],[0,1],[0,-1]]){const x=node.x+dx,y=node.y+dy;if(Math.abs(x)>21||Math.abs(y)>21||!free(x,y))continue;const k=key(x,y),old=nodes.get(k);if(old?.closed)continue;const worldX=(startX+x)*TILE+TILE/2,worldY=(startY+y)*TILE+TILE/2,hazard=tileHazardAt(worldX,worldY),cost=node.g+1+(hazard===HAZARD_LAVA?8:hazard?1:0);if(old&&old.g<=cost)continue;const next={x,y,g:cost,f:cost+Math.abs(x-end.x)+Math.abs(y-end.y),parent:node};nodes.set(k,next);open.push(next);}}path=[];while(last?.parent){path.unshift({x:(startX+last.x)*TILE+TILE/2,y:(startY+last.y)*TILE+TILE/2});last=last.parent;}}
 while(path.length&&Math.hypot(path[0].x-p.x,path[0].y-p.y)<19)path.shift();return path[0]||goal;}
 function control(){const g=game,p=g.player;let goal;
 if(config.route==='stationary'){g.joystick.active=false;g.joystick.dx=g.joystick.dy=0;return;}
 if(config.route==='explore'){const shrine=Object.values(g.routeEvents).find(e=>!e.done&&Number.isFinite(e.x)&&Math.hypot(e.x-p.x,e.y-p.y)<1400);const destination=!heartCleared('west')?'west':BIOME_IDS.filter(id=>!heartCleared(id)).sort((a,b)=>dist(p,chestPos(a))-dist(p,chestPos(b)))[0];goal=shrine||(destination?chestPos(destination):anchor);if(shrine&&dist(p,shrine)<45&&g.enemies.every(e=>e.dead||dist(p,e)>120)){g.joystick.active=false;return;}}
 else{const angle=g.time*.00055;goal={x:anchor.x+Math.cos(angle)*650,y:anchor.y+Math.sin(angle)*650};}
 let bestPickup=null,bestPickupScore=Infinity;for(const pickup of g.pickups){const d=dist(p,pickup);if(d>500)continue;const score=d/(pickup.type==='health'&&p.hp<p.maxHp*.65?3:pickup.type==='magnet'?2:1);if(score<bestPickupScore){bestPickupScore=score;bestPickup=pickup;}}
 if(bestPickup&&(config.route!=='explore'||dist(p,bestPickup)<260))goal=bestPickup;
 chosenGoal=goal;const aim=navigate(goal),goalAngle=Math.atan2(aim.y-p.y,aim.x-p.x);
 const threats=g.enemies.filter(e=>!e.dead&&dist(p,e)<550).sort((a,b)=>dist(p,a)-dist(p,b)).slice(0,25);let best=-Infinity,bestAngle=goalAngle;
 for(let i=0;i<24;i++){const angle=goalAngle+(i-12)*PI2/24,dx=Math.cos(angle),dy=Math.sin(angle);let score=Math.cos(angle-goalAngle)*48;const distance=Math.min(70,p.speed*.35);let blocked=false;for(const d of [12,32,distance])if(!passable(p.x+dx*d,p.y+dy*d)){blocked=true;break;}if(blocked)continue;const x=p.x+dx*distance,y=p.y+dy*distance;for(const enemy of threats){const separation=Math.hypot(x-enemy.x,y-enemy.y)-enemy.radius-p.radius;score-=Math.max(0,140-separation)*.45;if(separation<15)score-=160;}for(const projectile of g.castProjectiles){if(dist(p,projectile)>250)continue;const separation=Math.hypot(x-projectile.x,y-projectile.y);if(separation<50)score-=100;}const hazard=tileHazardAt(x,y);if(hazard===HAZARD_LAVA)score-=220;else if(hazard)score-=6;if(score>best){best=score;bestAngle=angle;}}
 g.joystick.active=true;g.joystick.dx=Math.cos(bestAngle);g.joystick.dy=Math.sin(bestAngle);}
 const dt=1000/60,startWall=performance.now();
 try{for(let frame=0;frame<config.seconds*60&&!game.gameOver;frame++){if(game.warpOpen)closeWarpMenu(true);if(game.paused)throw Error("Unexpected pause in simulated run");if(frame%6===0)control();const px=game.player.x,py=game.player.y;game.running=true;update(dt);game.running=false;ledger.lowHPSeconds+=game.player.hp<game.player.maxHp*.25?dt/1000:0;if(game.joystick.active&&Math.hypot(game.player.x-px,game.player.y-py)<.05)ledger.stuckSeconds+=dt/1000;
 if(game.time>=nextSnapshot){const p=game.player;ledger.snapshots.push({seconds:Math.round(game.time/1000),level:p.level,hp:+p.hp.toFixed(1),maxHp:p.maxHp,kills:game.kills,enemies:game.enemies.length,difficulty:+game.difficultyMult.toFixed(2),radialTiles:Math.round(Math.hypot(p.x,p.y)/TILE),weapons:p.weapons.map(w=>w.id+':'+w.level),vamp:+p.vamp.toFixed(3),regen:+p.regen.toFixed(2),armor:+p.armor.toFixed(2),biome:playerBiome()});nextSnapshot+=30000;}
 if(frame%600===599){await new Promise(resolve=>setTimeout(resolve,0));if(frame%3600===3599&&window.balanceProgress)await window.balanceProgress({case:config.name,seconds:Math.round(game.time/1000),level:game.player.level,kills:game.kills,hp:Math.round(game.player.hp),enemies:game.enemies.length});}}
 const p=game.player;return{config,death:game.gameOver,seconds:+(game.time/1000).toFixed(1),level:p.level,hp:+p.hp.toFixed(1),maxHp:p.maxHp,kills:game.kills,spawned:game.totalEnemiesSpawned,shards:game.essenceCollected,shrines:Object.values(game.routeEvents).filter(e=>e.done&&Number.isFinite(e.x)).length,difficulty:+game.difficultyMult.toFixed(2),weapons:p.weapons.map(w=>({id:w.id,level:w.level,evolution:w.evolution||null})),passives:p.passives,recipes:Object.keys(game.recipesTriggered),finalBiomes:game.discoveredBiomes,simulationWallSeconds:+((performance.now()-startWall)/1000).toFixed(2),ledger};
 }finally{autoPick=originalPick;gainXp=originalGain;damageEnemy=originalDamage;spawnGuardian=originalGuardian;killEnemy=originalKill;}
};
